[package]
name = "ecdsa"
version = "0.1.0"
edition = "2024_07"

[executable]

[profile.proving.cairo]
enable-gas = false

[dependencies]
cairo_execute = "2.12.0"
garaga = { git = "https://github.com/keep-starknet-strange/garaga", tag = "v0.18.2" }
